name: Rust

on:
  push:
    branches: ["main"]
    paths-ignore: ["**.md"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["**.md"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    concurrency:
      group: ci-rust-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Setup WASI
        run: rustup target add wasm32-wasi
      - name: Check with Clippy
        run: cargo clippy --target wasm32-wasi
